# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03820975b709700e1ac0c492996d61d0fd132d3da1e79e681816f214215da94a0d84b18b4d00e4599efa71388abde117134874c09a02f1027c7d58c30f04912a

test:
  secret_key_base: 5563af9c98f09bc4e1c2af497278bdc8712512a15ff2465688cd5c63e933991012d990d4696b23d814952a6f1b9f7c154ff67fa6be54a939b43b56c71e534bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
